spring:
  application:
    name: websocket
  datasource:
    # MariaDB JDBC 드라이버 클래스 이름

    # DB 연결 URL
    # (localhost의 3306 포트에 있는 WebSocket DB에 연결)
    url: jdbc:postgresql://localhost:5432/chatdb
    username: devuser
    password: 35703570pp

    # (JPA를 사용하시는 경우 추가)
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
    show-sql: true
